### ISSUE TITLE
Criar Roadmap geral do projeto.

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#105]
# Descrição
Esta issue se dedicará a criação do roadmap geral do projeto, conforme os [templates obtidos](https://fga-eps-mds.github.io/2021.2-INDICAA/#/roadmaps/).

# Tarefas
- [x] Criar o template para os roadmaps do projeto INDICAA.
- [x] Definir os itens do roadmap geral do projeto.
- [x] Criar o roadmap geral do projeto.
- [x] Adicionar ao repositório o roadmap geral do projeto.

# Critérios de aceitação
- [x] Roadmap geral do projeto criado e adicionado ao repositório
- [ ] Link para o template criado e adicionado ao meio de comunicação oficial do projeto.
- [x] Revisão do roadmap geral do projeto.

**Comment by LeticiaAires** [comment]
Segue link para Roadmap geral do projeto: https://www.canva.com/design/DAE8kefIH0E/rFzLkLbe305-vnrdib2bPw/view?utm_content=DAE8kefIH0E&utm_campaign=share_your_design&utm_medium=link&utm_source=shareyourdesignpanel
Favor revisar.

**Comment by Matheuspleal** [comment]
O item "disponibilizar na play store" não se encaixa no roadmap geral do projeto por não ser um app que estamos desenvolvendo, e sim um website com front-end no Metabase.

**Comment by LeticiaAires** [comment]
https://www.canva.com/design/DAE8kefIH0E/rFzLkLbe305-vnrdib2bPw/view?utm_content=DAE8kefIH0E&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink
prontinho!

**Comment by Matheuspleal** [comment]
Ficou muito bom, Letícia!! Vamos pedir revisão à alguem ?

**Comment by mc-gomes** [comment]
Analisei o Roadmap e parece bem adequado, muito bom !
