### ISSUE TITLE
Revisão dos documentos do projeto.

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#110]
# Descrição
Esta é uma issue recorrente (se repete 1x por sprint) e tem como objetivo a revisão geral da documentação produzida pelo projeto. A revisão se dará à partir da branch develop.

# Documentos
- [x] dicionario_de_dados.md.
- [x] documento_de_arquitetura.md.
- [x] documento_de_metodologia.md.
- [x] documento_de_visao.md.
- [x] documento_requisitos.md.
- [x] estrutura_analitica_do_projeto.md.
- [x] gerenciamento_de_comunicação.md
- [x] gerenciamento_de_riscos.md.
- [x] guia_Branching.md.
- [x] prototipos.md.
- [x] style_guide.md.
- [x] termo_de_abertura.md.

# Tarefas
- [x] Padronizar os nomes de arquivos de documentação.
- [x] Revisão dos conceitos abordados por cada documento.
- [x] Adição de novos conceitos em seus documentos correspondentes.
- [x] Remoção de conceitos antigos ou não atualizados nos documentos.

**Comment by Matheuspleal** [comment]
# Divisão da revisão dos conteúdos dos arquivos

## Arthur

dicionario de dados
guia de estilo
documento de metodologia
documento de requisitos
gerenciamento de comunicação
guia de branching

## Matheus

documento de arquitetura
documento de visão
estrutura analitica do projeto
gerenciamento de riscos
prototipos
termo de abertura

**Comment by Matheuspleal** [comment]
## Parão de nomes dos arquivos

totalmente em português, todas as letras minúsculas, sem acentos

nome_do_documento.<extensao>

extensao pode ser: md, txt, png, jpg, svg, ...

se o arquivo tiver 2 ou mais partes:

nome_do_documento-1.<extensao>

nome_do_documento-2.<extensao>

**Comment by Matheuspleal** [comment]
A revisão do documento de protótipos foi finalizada ontem no repositório wiki.

**Comment by Matheuspleal** [comment]
Hoje, irá ser feita uma nova revisão que vai elvar em consideração os documentos presentes no git pages da branch develop do repositório [2021.2-INDICAA-Wiki](https://github.com/fga-eps-mds/2021.2-INDICAA-Wiki)

**Comment by Matheuspimentell** [comment]
Foi finalizada a revisão dos documentos do projeto.
