### ISSUE TITLE
Refatoração individual dos scripts de scraping da FACULDADE DO GAMA - BRASÍLIA

### ISSUE THREAD

**Issue by MorettiGS** [fga-eps-mds/2021.2-INDICAA#111]
# Descrição
Nesta issue, os scripts criados para o scraping dos dados na FGA (Faculdade do Gama - Brasília) terão seus dados refatorados, sendo esses alterados para estar de acordo com o dicionário de dados encontrado [aqui](https://github.com/fga-eps-mds/2021.2-INDICAA/blob/develop/docs/documentacao/dicionario_de_dados.md).

# Tarefas
- [x] Observar os nomes padrões dos dados no dicionário de dados .
- [x] Padronizar os nomes dos dados retornados no código da issue #93 .
- [x] Padronizar os nomes dos dados retornados no código da issue #86 .
- [x] Padronizar os nomes dos dados retornados no código da issue #92 .

# Critérios de aceitação
- [x] Os nomes dos dados devem estar de acordo com o dicionário de dados em todos os códigos.
- [x] Os códigos devem ser revisados.

**Comment by MorettiGS** [comment]
# Padrão de nomes

Esses são os nomes presentes no dicionário de dados:

## Departamento

- 'nome': nome do departamento

## Materia 

- 'codigoMateria' : código da matéria em questão
- 'cargaHoraria' : carga horária da matéria
- 'nome' : nome da matéria

## Turma

- 'docente' : nome completo do docente da turma
- 'codigoTurma' : código da turma
- 'horario' : horário da turma
- 'vagasOfertadas' : quantidade de vagas ofertadas
- 'vagasOcupadas' : quantidade de vagas ocupadas
- 'local' : local da aula da turma
- 'ano' : ano do período
- 'semestre' : semestre do período

**Comment by MorettiGS** [comment]
Com os commits realizados, foram feitas as devidas mudanças nos seguintes arquivos:

- QtdeAlunosMatriculados.py
- QtdeVagasOfertadas.py

Visto que o arquivo QtdVagasDisponiveis.py não trará nenhuma adição significativa para os dados e provavelmente não será utilizado posteriormente, ele não foi padronizado.

Portanto, a issue pode ser revisada, levando em conta apenas os dois documentos acima e seus nomes de **variáveis** e **chaves dos dicionários**, seguindo, como solicitado, o padrão do dicionário de dados.

**Comment by gabrielm2q** [comment]
Os nomes das variáveis conferem com o que prevê o dicionário de dados. Cabe apenas a organização destas de modo que cada script retorne apenas o que é pedido, haja vista que alguns dicionários estão retornando dados discrepantes do que prevê o Dicionário de Dados, além da existência de alguns dicionários "desnecessários".

Talvez seja interessante, realizar uma mudança de nome da dict "turmas" (QtdeAlunosMatriculados, linha 82) para "turma", mas tal revisão pode ser realizada na refatoração dos scripts.

O princípio da _issue_ foi realizado (padronizar nomes das variáveis de acordo com o Dicionário de Dados) e as mudanças citadas anteriormente cabem à outra _issue_.

Revisão realizada
