### ISSUE TITLE
Scraping dos dados restantes - Dicionário de dados

### ISSUE THREAD

**Issue by MorettiGS** [fga-eps-mds/2021.2-INDICAA#112]
# Descrição
Nesta issue, os scripts criados para o scraping dos dados na FGA (Faculdade do Gama - Brasília) terão seus retornos analisados e, de acordo com o dicionário de dados encontrado [aqui](https://github.com/fga-eps-mds/2021.2-INDICAA/blob/develop/docs/documentacao/dicionario_de_dados.md), será realizado o scraping dos dados restantes (caso necessário).

# Tarefas
- [x] Perguntar para os responsáveis pelas issues #86 , #92 e #93 quais são os dados que faltam ser retornados em cada entidade.
- [x] Realizar o scraping dos dados faltantes no código da issue #86 .
- [x] Realizar o scraping dos dados faltantes no código da issue #92 .
- [x] Realizar o scraping dos dados faltantes no código da issue #93 .

# Critérios de aceitação
- [x] Todos os dados do dicionário de dados devem ser retornados pelos códigos das issues em questão.
- [x] O código referente à issue #86 deve ser revisado.
- [x] O código referente à issue #92 deve ser revisado.
- [x] O código referente à issue #93 deve ser revisado.

**Comment by gabrielm2q** [comment]
# Dicionário de Dados
Em um primeiro momento, verificaremos todos os dados que devem ser puxados, levando em consideração o que diz o [Dicionário de Dados](https://github.com/fga-eps-mds/2021.2-INDICAA/blob/develop/docs/documentacao/dicionario_de_dados.md).

# Unidade
- nome

# Matéria
- código da matéria
- carga horária
- nome da matéria

# Turma
- nome do docente
- código da turma
- horário
- número de vagas ofertadas
- número de vagas ocupadas
- local das aulas
- ano
- semestre

**Comment by gabrielm2q** [comment]
# Situação atual
Da maneira que estão situados, os códigos existentes já retornam os seguintes dados:

# mapeamento_materias
- código da matéria
- nome da matéria

# QtdeAlunosMatriculados
- nome (da unidade)
- nome do docente
- número de vagas ocupadas (por turma, por matéria e total)
- carga horária (turma)
- nome da matéria
- código da matéria

# QtdeVagasOfertadas
- número de vagas ofertadas (por turma)
- nome do docente
- carga horária (por turma)

# QtdVagasDisponiveis
- nome do docente
- carga horária
- número vagas disponíveis (vagas ofertadas - vagas ocupadas)

**Comment by MorettiGS** [comment]
# Dicionário de dados

Dados a serem adicionados aos retornos atuais:

## Matérias

- código da turma
- horário
- local das aulas
- ano
- semestre

**Comment by gabrielm2q** [comment]
Foi realizado, até o momento, o _scraping_ do Código e do Horário de cada turma.

Tais alterações foram adicionadas ao script "QtdeAlunosMatriculados".

**Comment by MorettiGS** [comment]
Com esse último commit, foi realizado o _scraping_ do Ano e do Semestre de cada turma.

Tais alterações foram adicionadas ao script "QtdeAlunosMatriculados".

**Comment by MorettiGS** [comment]
Foi realizado o scraping do Local de cada turma, assim finalizando o processo da issue.

Tais alterações foram adicionadas ao script "QtdeAlunosMatriculados".

Portanto, essa issue pode ser revisada, de preferência aceitando logo em seguida o Pull Request gerado.

**Comment by AdneMoretti** [comment]
Bom dia! Acabei de revisar a issue e o código de todas as issues relacionadas. Ta tudo de acordo com a descrição.
