### ISSUE TITLE
Criar Roadmap Geral (Como executado)

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#121]
# Descrição
Com o roadmap geral já criado, esta issue se dedicará a fazer uma versão "como executada" do documento em questão.

# Tarefas
- [x] Criar o documento de roadmap geral (como executado).
- [x] Adicionar os passos executados até então.

# Critérios de aceitação
- [x] O documento em questão deve estar adicionado ao repositório de documentações.
- [ ] O documento em questão deve ser revisado.
- [ ] O documento em questão deve ser adicionado ao novo git pages.

**Comment by LeticiaAires** [comment]
Segue o link do roadmap como executado para revisão: https://www.canva.com/design/DAE9Cgn1cLA/4QiqVn_SUItEs8nWi6Geuw/edit?utm_content=DAE9Cgn1cLA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Matheuspleal** [comment]
Vou revisar pra você hoje!!

**Comment by LeticiaAires** [comment]
https://www.canva.com/design/DAE9Cgn1cLA/4QiqVn_SUItEs8nWi6Geuw/view?utm_content=DAE9Cgn1cLA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Matheuspleal** [comment]
O roadmap está de acordo com o que foi executado até o momento! Falta apenas completar os itens conforme forem aparecendo.

**Comment by Matheuspleal** [comment]
A issue pode ser finalizada. @LeticiaAires

**Comment by LeticiaAires** [comment]
ok!
