### ISSUE TITLE
Vídeo de apresentação individual dos grupos

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#148]
# Descrição
Para a release 2, foi solicitado que cada grupo fizesse um vídeo como "retrospectiva" da matéria. As especificações necessárias estão descritas [aqui](https://github.com/fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps/issues/37).

# Tarefas
- [x] Grupo 01: Fazer o vídeo.
- [x] Grupo 03: Fazer o vídeo.
- [x] Grupo 04: Fazer o vídeo.
- [x] Grupo 01: Postar o vídeo.
- [x] Grupo 03: Postar o vídeo.
- [x] Grupo 04: Postar o vídeo.

# Critérios de aceitação
- [x] Grupo 01: Vídeo postado como comentário da issue fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps#37.
- [x] Grupo 03: Vídeo postado como comentário da issue fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps#37.
- [x] Grupo 04: Vídeo postado como comentário da issue fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps#37.

**Comment by oCaioOliveira** [comment]
## Roteiro e Dicas para Vídeo de Apresentação da Release 2 do Grupo 1
  - No começo das nossas falas devemos sempre nos apresentar e falar nossas funções atuais na equipe;
  - Cada um deve falar de um tópico e a edição deve ser feita na ordem:
    1° - Editor - Apresentação própria, apresentação resumida sobre o projeto e gancho para a entrada da equipe (1 min);
    2° - XXXX - Apresentar as lições aprendidas da squad(2 min);
    3° - XXXX- Apresentar a visão critica sobre a execução das práticas ágeis (como o time ve a relação das praticas ágeis e a produtividade)(2:30 min);
    4° - XXXX - Apresentar as métricas do time (velocity, burndowns, qte de pontos entregues)(2 min);
    5° - XXXX- Apresentar o escopo que o time entregou durante a disciplina (responsabilidades, atribuições)(2:30 min);
    6° - XXXX - O que poderia ser feito melhor e sugestões para próximos semestres(2 min).

**Comment by vitorekr** [comment]
> ## Roteiro e Dicas para Vídeo de Apresentação da Release 2 do Grupo 1
> * No começo das nossas falas devemos sempre nos apresentar e falar nossas funções atuais na equipe;
> * Cada um deve falar de um tópico e a edição deve ser feita na ordem:
>   1° - Vitor - Apresentação própria, apresentação resumida sobre o projeto e gancho para a entrada da equipe (1 min);
>   2° - Caio - Apresentar as lições aprendidas da squad(2 min);
>   3° - Matheus - Apresentar a visão critica sobre a execução das práticas ágeis (como o time ve a relação das praticas ágeis e a produtividade)(2:30 min);
>   4° - Lucas - Apresentar as métricas do time (velocity, burndowns, qte de pontos entregues)(2 min);
>   5° - Laura - Apresentar o escopo que o time entregou durante a disciplina (responsabilidades, atribuições)(2:30 min);
>   6° - Letícia - O que poderia ser feito melhor e sugestões para próximos semestres(2 min).

Video editado e postado no youtube seguindo esta sequência.
