### ISSUE TITLE
Desenvolvimento do gitpages

### ISSUE THREAD

**Issue by guigudf** [fga-eps-mds/2021.2-INDICAA#19]
# Descrição
Desenvolver o Gitpages

# Tarefas
- [x] Documentação presente no site 
- [x] Redirecionamento do site para o repositório

# Critérios de aceitação
- [x] Pagina do gitpages funcionando 
- [x] Outra pessoa conseguir acessar a url

**Comment by Matheuspleal** [comment]
Para a R1, este épico cumpriu todos os objetivos propostos
