### ISSUE TITLE
Community Standards

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#35]
# Descrição
Completar a seção de community standards do repositório do projeto

# Tarefas
- [x] Adicionar "Contributing" ao repositório
- [x] Adicionar "Code of conduct" ao repositório
- [x] Adicionar "Commit templates" ao repositório
- [x] Adicionar "Issue templates" ao repositório
- [x] Adicionar "Description" ao repositório
- [x] Adicionar "Pull request templates" ao repositório

# Critérios de aceitação
- [x] Todos os itens que compõem o community standards devem estar devidamente visíveis e preenchidos

**Comment by Matheuspleal** [comment]
Como todos os community Standards foram cumpridos :tada:, estarei fechando este épico.
