### ISSUE TITLE
Vídeo de apresentação do grupo 03.

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#65]
# Tarefas
- [x] Definir roteiro.
- [x] Gravação do vídeo (E edição, caso necessário).
- [x] Postagem do vídeo para que outras pessoas consigam ver (Postar no YouTube, Drive, etc...).
- [x] Postagem de um comentário com o link do vídeo na [issue criada pela professora](https://github.com/fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps/issues/33).

# Critérios de aceitação
- [x] O vídeo deve possuir boa qualidade de som e imagem.
- [x] O vídeo deve seguir o template proposto na [issue criada pela professora](https://github.com/fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps/issues/33).
- [x] Todos os tópicos definidos devem ter sido abordados.
- [x] O projeto deve ter sido explicado sucintamente no vídeo.
- [x] O vídeo deve ter sido postado em plataforma pública.
- [x] O link para o vídeo deve ter sido disponibilizado na [issue criada pela professora](https://github.com/fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps/issues/33).

**Comment by gabrielm2q** [comment]
# **ROTEIRO DO VÍDEO DE APRESENTAÇÃO DO GRUPO 03:**
1. Falar da definição dos papéis SCRUM (Guilhmerme)
  - S.M.: Matheus Pimentel
  - P.O. : Adne Moretti
  - DevOps: Gabriel Mariano
  - Dev: Gabriel Moretti
  - Arquiteto: Guilherme Barbosa
  

2. Apresentação
    2.1. Comunicação (Adne)
    - A comunicação entre o grupo 03 (nós) foi constante, porém a comunicação entre grupos deixou a desejar, e nós vemos nisso uma oportunidade de melhoria
    - A comunicação entre o grupo foi feita a partir de mensagens no grupo criado no *Telegram* e as reuniões foram feitas no *Discord* em horários previamente combinados
    
    2.2 Riscos (Gabriel Mariano)
      
    -  Como foram contornados os riscos previstos que realmente ocorreram: 
        - Desistência de um membro: Reavaliação dos pesos das tarefas e melhor distribuição destas
        - Falha na comunicação entre os grupos: Os grupos foram contatados via mensagens no grupo geral do *Telegram*
        - Atrasos nas entregas de tarefas: Análise dos motivos e redistribuição
    
    2.3 Produtividade (Gabriel Moretti)
    - As tarefas do grupo foram executadas de forma produtiva e eficaz
    - Durante a execução de algumas sprints foi detectado que a distribuição das tarefas estava falha e, por isso, uma melhor distribuição foi discutida com os membros do grupo para aumentar a produtividade
    
    2.4 O que foi feito de "muito bom" (Guilherme Barbosa)
    - Pesquisas
    - Proatividade
  
    2.5 O que foi ruim (Matheus Pimentel)
    - A distribuição das tarefas estava precária, porém foi melhorado durante as sprints
    - A comunicação com os outros grupos
    - A organização dos commits
    
    2.6 Qual a principal melhoria (Matheus Pimentel)
    - Dailies a serem implementadas
   
3. Práticas ágeis que mais adotamos (G Moretti)
  - Planning / Review
  - Kanban (Zenhub)
  - Pair Programming (documenting)
  - Planning poker (implementado nas sprints mais recentes)

4. Cada membro dá as suas visões críticas
  - Adne Moretti fala;
  - Gabriel Mariano fala;
  - Gabriel Moretti fala;
  - Guilherme Barbosa fala;
  - Matheus Pimentel fala.

**Comment by gabrielm2q** [comment]
O [link para o vídeo](https://youtu.be/NJ0z38k37ak) foi postado na [issue](https://github.com/fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps/issues/33#issuecomment-1061325892) criada pela professora.
