### ISSUE TITLE
Vídeo de apresentação do grupo 01.

### ISSUE THREAD

**Issue by LeticiaAires** [fga-eps-mds/2021.2-INDICAA#67]
# Tarefas
- [x] Definir roteiro em conjunto.
- [x] Gravação e edição do vídeo.
- [x] Postagem do vídeo em plataforma pública.
- [x] Postagem de um comentário com o link do vídeo na [issue criada pela professora](https://github.com/fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps/issues/33).

# Critérios de aceitação
- [x] O vídeo deve possuir boa qualidade de som e imagem.
- [x] O vídeo deve seguir o template proposto na [issue criada pela professora](https://github.com/fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps/issues/33).
- [x] Todos os tópicos definidos devem ter sido abordados.
- [x] O vídeo deve poder ser acessado por todos.
- [x] O link para o vídeo deve ter sido disponibilizado na [issue criada pela professora](https://github.com/fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps/issues/33).

**Comment by oCaioOliveira** [comment]
## Roteiro e Dicas para Vídeo de Apresentação da Release 1
  - Cada um deve falar entre 30-40 segundos (podendo variar em tópicos maiores ou menores), por o tempo ser curto devemos focar em falas diretas e curtas, porém claras;
  - No começo das nossas falas devemos sempre nos apresentar e falar nossas funções atuais na equipe;
  - No final das nossas falas devemos mostrar nossa visão critica em relação ao projeto caso sobre tempo;
  - Cada um deve falar de um tópico e a edição deve ser feita na ordem:
    1° - Vitor - Apresentação própria, visão crítica e gancho para a entrada da equipe;
    2° - Caio - Comunicação e Riscos;
    3° - Lucas - Entender como aplicamos as praticas ágeis (scrum + kanban + relação entre squads);
    4° - XXXXX - Como as praticas ágeis refletiram na produtividade;
    5° - Letícia - O que foi feito muito bom pelo time e O que foi ruim;
    6° - XXXXX - Qual a principal melhoria vcs querem adotar para a release 2;

**Comment by vitorekr** [comment]
https://youtu.be/_5XcDSRZ6IQ
