### ISSUE TITLE
Vídeo de apresentação do grupo 04.

### ISSUE THREAD

**Issue by guigudf** [fga-eps-mds/2021.2-INDICAA#68]
# Tarefas
- [ ] Definir roteiro.
- [ ] Gravação do vídeo (E edição, caso necessário).
- [ ] Postagem do vídeo para que outras pessoas consigam ver (Postar no YouTube, Drive, etc...).
- [ ] Postagem de um comentário com o link do vídeo na [issue criada pela professora](https://github.com/fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps/issues/33).

# Critérios de aceitação
- [ ] O vídeo deve possuir boa qualidade de som e imagem.
- [ ] O vídeo deve seguir o template proposto na [issue criada pela professora](https://github.com/fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps/issues/33).
- [ ] Todos os tópicos definidos devem ter sido abordados.
- [ ] O projeto deve ter sido explicado sucintamente no vídeo.
- [ ] O vídeo deve ter sido postado em plataforma pública.
- [ ] O link para o vídeo deve ter sido disponibilizado na [issue criada pela professora](https://github.com/fga-eps-mds/Qualifying-Software-Engineers-Undergraduates-in-DevOps/issues/33).
