### ISSUE TITLE
Criação da API com o Django Rest

### ISSUE THREAD

**Issue by Matheuspleal** [fga-eps-mds/2021.2-INDICAA#89]
# Descrição
Para o _Back-End_ do projeto, foi determinado que iremos fazer a criação de uma _API_ com o _framework_ [Django Rest](https://www.django-rest-framework.org/). Esta issue se dedicará à criação da primeira versão da _API_ citada.

# Tarefas
- [x] Criar a branch de feature a partir da branch develop.
- [x] Criar o projeto _Django_.
- [x] Criar a API do projeto
- [x] #116
- [x] Documentar as decisões tomadas em formato de comentário nesta issue.

# Critérios de aceitação
- [x] Branch feature criada.
- [x] Todos os commits relacionados devem estar a branch feature criada.
- [x] A _API_ deve estar guardando os dados do SIGAA.
- [x] Pull Request criado ao final do desenvolvimento inicial da _API_.
- [x] Todas as decisões tomadas devem estar documentadas nesta issue.

**Comment by RochaCarla** [comment]
Essa issue está confusa..  nao está claro o que significa "lógica de scraping".. a falta de escopo bem delimitado aumenta a probabilidade de vcs nao conseguirem fechar a issue em um ciclo de sprint

**Comment by Mateusvff** [comment]
@Matheuspleal Não seria melhor criarmos um repositório para o Backend igual criamos para o frontend?

**Comment by Matheuspleal** [comment]
> @Matheuspleal Não seria melhor criarmos um repositório para o Backend igual criamos para o frontend?

Acredito que podemos usar esse repositório aqui mesmo, você acha que é melhor criar um repositório só pro backend mesmo ?

**Comment by Mateusvff** [comment]
Mas aí pode colocar da API dos projetos normalmente dentro do repositório?

**Comment by oCaioOliveira** [comment]
Reunião realizada e desenvolivmento da API em django rest foi iniciado, após discussão sobre criar um repositório novo ou não será publicada. Participantes: @oCaioOliveira @Mateusvff @Eruel6.

**Comment by Matheuspleal** [comment]
> Mas aí pode colocar a pasta da API normalmente dentro do repositório?

Se for manter esse repositório, só basta criar uma boa estrutura de pastas bem feita, daí fica tranquilo a organização. O que você acha ??

**Comment by Mateusvff** [comment]
Pode ser então! Vamos criar uma pasta chamada 'backend' e ir colocando dentro dela, pode ser?
Eu, o @Eruel6 e o @oCaioOliveira criamos a estrutura básica aqui da API e já definimos as próximas reuniões e o que devemos fazer até lá. Vamos subir pro repositório.
Por enquanto só temos rodando localmente, depois subir para um servidor!

**Comment by oCaioOliveira** [comment]
Complementando o comentário do @Mateusvff, decidimos fazer um documento com um modelo e diagramas sobre o banco de dados a ser criado.

**Comment by oCaioOliveira** [comment]
Definida reunião dia 29/03 as 19:00 para evoluir a API do projeto.

**Comment by oCaioOliveira** [comment]
## Diagrama de Entidade-Relacionamento do Projeto:

![mds](https://user-images.githubusercontent.com/54439337/160719003-bd98bf09-3b8f-44e1-b096-0e50291d02b1.png)

**Comment by oCaioOliveira** [comment]
## Ata da Reunião 29/09
Na reunião do dia 29/09 de duração de 02 horas e participação de @Mateusvff, @mc-gomes, @AdneMoretti e @oCaioOliveira houve a criação do Diagrama de Entidade-Relacionamento do Projeto, desenvolvimento maior do código que já está atualizado com os commits descrevendo o que foi feito em cada atualização.

**Comment by Matheuspleal** [comment]
Eu concordo!

**Comment by oCaioOliveira** [comment]
Código foi evoluído e adicionado as entidades que faltavam, encontrei um impedimento onde o banco de dados não aceita chave primária composta, estou correndo atrás para utilizar chaves únicas e contornar o problema, assim que for corrigido isso o código será feito o commit.

**Comment by oCaioOliveira** [comment]
## Ata da Reunião 04/04
Na reunião do dia 04/04 de duração de 02 horas e participação de @Mateusvff, @Eruel6 e @oCaioOliveira resultou em evoluções em relação ao deploy da API no heroku, no final do processo encontramos alguns erros inesperados e como estávamos todos cansados, decidimos deixar isso para amanhã.

**Comment by AdneMoretti** [comment]
Boa noite galera, fiz um commit aqui onde eu mudo as pastas da api pra dentro da raiz (src), isso foi feito para que as pastas fiquem mais organizadas e com mais cara de um projeto, além de facilitar a comunicação com os códigos de scraping, para eles, foi criada a pasta scraping. No lugar do arquivo tests.py coloquei uma pasta tests, pois no decorrer do projeto teremos que fazer mais de um arquivo para teste.

Além disso, mudei também o nome das pastas, a pasta `myapi` passou a ser passou a ser `api` e a `mysite` se tornou `config`, por conter as configurações necessárias da api. A decisão para mudança de nome foi porque `mysite`e `myapi` fazem mais sentidos para projetos individuais. Caso vocês tenham alguma dúvida em relação a essas mudanças, podem falar comigo!

**Comment by AdneMoretti** [comment]
Criei também o arquivo pytest.ini que contém configurações para rodar o pytest com o django e o test_crud_unidade, onde comecei a fazer um teste de criação de uma Unidade do banco de dados.

**Comment by oCaioOliveira** [comment]
## Ata da Reunião 08/04
Na reunião do dia 08/04 de duração de 02 horas e participação de @Mateusvff e @oCaioOliveira resultou em evoluções em relação ao deploy da API no heroku, no final do processo conseguimos fazer o deploy no link a seguir: [indicaa-api](https://indicaa-unb-apii.herokuapp.com/). Agora todos da equipe tem acesso, entretando tivemos problemas ao fazer o commit das alterações na branch, entendemos que o git não conseguiu inserir o outro repositório criado no heroku, hoje tentaremos novamente fazer o commit com a atualização.

**Comment by Matheuspleal** [comment]
A API foi criada e melhorada durante as sprints seguintes. A issue será fechada.
